import Head from 'next/head';

export default function Home() {
  return (
    <div className="bg-black h-screen w-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className="text-white">Charlie Test</p>

      
    </div>
  )
}
